#!/bin/sh

neededchanged=`/usr/sbin/hwscan --mouse`
if [ -n "$neededchanged" ] ; then
	/sbin/yast2 mouse '(.reprobe)'
	for i in $neededchanged ; do
		/bin/rm /var/lib/hardware/$i
	done
fi
neededchanged=`/usr/sbin/hwscan --gfxcard`
if [ -n "$neededchanged" ] ; then
	/sbin/yast2 x11 '(.reprobe)'
	for i in $neededchanged ; do
		/bin/rm /var/lib/hardware/$i
	done
fi
/usr/sbin/hwscan --storage_ctrl
/usr/sbin/hwscan --network_ctrl
/usr/sbin/hwscan --tv
/usr/sbin/hwscan --sound
exit 0
