#! /usr/bin/perl

@l = (<>);

for ($i = 0; $i < @l; $i++) {
  if($l[$i] =~ /^\tx\t3/) {
    $l[$i - 1] = "# $l[$i - 1]";
    $l[$i] = "# $l[$i]";
    for ($j = 1;  $l[$i + $j] =~ /^\t\t/; $j++) {
      $l[$i + $j] = "# $l[$i + $j]";
    }
  }
}

print @l;

