#! /usr/bin/perl

sub cbits;
sub getit;
sub drop_xf;

for (@ARGV) {
  getit $_;
}

sub getit
{
  my ($file, $arch, @f, @f3, @f4);
  local $_;

  $file = shift;
  $arch = $file;
  $arch =~ s/.*\.//;
  $arch = 'ia32' if $arch eq 'i386';

  die "oops" unless open F, $file;

  @f = (<F>);
  close F;

  for (@f) {
    s/^(\tx\t.*?)XF86_([^|]+)/$1\U$2/;
    if(/^\tx\t/) {
      s/^(([^|]*\|){6})([0-9,]+)/$1 . cbits($3)/e;
    }
  }

  @f3 = drop_xf 4, @f;
  @f4 = drop_xf 3, @f;

  @f = grep { !/^(##|\s*$)/  } (@f4, @f3);
  map { s/^#/\n#/ } @f;

  die "oops" unless open W, ">drivers.x11.$arch";
  print W @f;
  close W;
  system "rm -f tmp.hwinfo";
}

sub cbits
{
  my $i;
  local $_;

  $i = 0;
  for (split /,/, $_[0]) {
    $i |=  1 if $_ ==  8;
    $i |=  2 if $_ == 15;
    $i |=  4 if $_ == 16;
    $i |=  8 if $_ == 24;
    $i |= 16 if $_ == 32;
  }

  return sprintf "%x", $i;
}


sub drop_xf
{
  my ($i, $j, @l, $v);

  ($v, @l) = @_;

  for ($i = 0; $i < @l; $i++) {
    if($l[$i] =~ /^\tx\t$v/) {
      $l[$i - 2] = "## $l[$i - 2]" if $l[$i - 2] =~ /^#/;
      $l[$i - 1] = "## $l[$i - 1]";
      $l[$i] = "## $l[$i]";
      for ($j = 1;  $l[$i + $j] =~ /^\t\t/; $j++) {
        $l[$i + $j] = "## $l[$i + $j]";
      }
    }
  }

  return @l;
}

