#! /usr/bin/perl -w

$name = @ARGV ? $ARGV[0] : "id_list";

while(<>) {
  s/(["\\])/\\$1/g;
  s/\t/\\t/g;
  s/\n/\\n/g;
  s/([\x00-\x1f])/sprintf("\\%03o", ord($1))/eg;
  $_ = "  \"$_\"";
  push @l, $_;
}

push @l, "  (char *) 0";

print "char \*$name\[\] = {\n", join(",\n", @l), "\n};\n";

