.\" Michal Svec <msvec@suse.cz>
.\"
.\" Process this file with
.\" groff -man -Tascii foo.1
.\"
.\"
.TH HWINFO 8 "January 2003" "hwinfo" "System configuration"
.\"
.\"
.SH NAME
hwinfo \- probe for hardware
.\"
.\"
.SH SYNOPSIS
.B hwinfo [
.I options
.B ]
.\"
.\"
.SH DESCRIPTION
.B hwinfo
is used to probe for the hardware present in the system. It can be used
to generate a system overview log which can be later used for support.
.\"
.\"
.SH OPTIONS
.\"
.TP
.BI --debug " " level
Set debug
.B level.
The debug info is shown only in the log file. If you specify a log file,
the debug level is implicitly set to a reasonable value.
.\"
.TP
.BI --dump-db " " n
Dump hardware data base,
.B n
is either
.B 0
for the external data base, or
.B 1
for the internal data base.
.\"
.TP
.BI --help
Print a usage and exit.
.\"
.TP
.BI --log " " logfile
Write info to
.B logfile.
.\"
.TP
.BI --short
Just a short listing.
.\"
.TP
.BI --version
Show libhd version.
.\"
.TP
.BI --<hwitem>
Probe for the particular hardware item. Available hardware items are:
.B all, bios, block, bluetooth, braille, bridge, camera, cdrom, chipcard, cpu,
.B disk, dsl, dvb, fingerprint, floppy, framebuffer, gfxcard, hub, ide, isapnp, isdn,
.B joystick, keyboard, memory, modem, monitor, mouse, netcard, network,
.B partition, pci, pcmcia, pcmcia-ctrl, pppoe, printer, scanner, scsi, smp,
.B sound, storage-ctrl, sys, tape, tv, usb, usb-ctrl, vbe, wlan,
and
.B zip.
.\"
.\"
.SH FILES
.B /var/lib/hardware/*
.\"
.\"
.SH BUGS
Not all hardware can be detected.
.\"
.\"
.SH AUTHOR
.nf
Steffen Winterfeldt <snwint@suse.de> - hwinfo
Michal Svec <msvec@suse.cz> - manual page
.fi
.\"
.\"
.SH "SEE ALSO"
Documentation in /usr/share/doc/packages/hwinfo.
.\"
.\" EOF
