#! /bin/sh

# check in hwinfo to /work/src/done/STABLE
# call from the hwinfo directory

ver=`cat VERSION`
hwinfo=/tmp/hwinfo-$ver

make clean
rm -rf $hwinfo
mkdir $hwinfo
tar -cf - * | tar -C $hwinfo -xf -
cd $hwinfo
find . -depth -name CVS -exec rm -r {} \;
find . -depth -name .cvsignore -exec rm -r {} \;
cd src/ids
mkdir .x
mv Makefile.dist .x/Makefile
mv drivers.sample README* names.sample names.bus names.class mk_ids .x
rm -rf old
rm *
mv .x/* .
rm -r .x
cd ../..
rm MAINTAINER scripts/ci_*
cd /tmp

tar -Icf $hwinfo.tar.bz2 hwinfo-$ver

if mkdir /work/src/done/STABLE/hwinfo ; then
  cd /work/src/done/STABLE/hwinfo
  cp $hwinfo.tar.bz2 /work/SRC/all/hwinfo/hwinfo.{changes,spec} .
  perl -pi -e 's/^(Version:\s+)\S+/${1}'$ver'/' /work/src/done/STABLE/hwinfo/hwinfo.spec
  perl -pi -e 's/^(Source.+?-)\S+?(\.tar\.bz2)/${1}'$ver'${2}/' /work/src/done/STABLE/hwinfo/hwinfo.spec
  . /work/src/bin/.profile
  vc hwinfo
  rm /work/src/done/STABLE/hwinfo/*~
  echo "done"
else
  echo oops
  exit 1
fi

