#! /bin/sh

# check in libhd to /work/src/done/STABLE
# call from the libhd directory

ver=`cat VERSION`
libhdint=/tmp/libhdint-$ver

make clean
rm -rf $libhdint
mkdir $libhdint
tar -cf - src/ids | tar -C $libhdint -xf -
cd $libhdint
find . -depth -name CVS -exec rm -r {} \;
find . -depth -name .cvsignore -exec rm -r {} \;
rm -f MAINTAINER scripts/ci_*
cd /tmp

tar -zcf $libhdint.tar.gz libhdint-$ver

if mkdir /work/src/done/STABLE/libhdint ; then
  cd /work/src/done/STABLE/libhdint
  cp $libhdint.tar.gz /work/SRC/all/libhdint/libhdint.{changes,spec} .
  perl -pi -e 's/^(Version:\s+)\S+/${1}'$ver'/' /work/src/done/STABLE/libhdint/libhdint.spec
  perl -pi -e 's/^(Source.+?-)\S+?(\.tar\.gz)/${1}'$ver'${2}/' /work/src/done/STABLE/libhdint/libhdint.spec
  . /work/src/bin/.profile
  vc libhdint
  rm /work/src/done/STABLE/libhdint/*~
  echo "done"
else
  echo oops
  exit 1
fi
