#! /bin/sh

# check in libhd to /work/src/done/STABLE
# call from the libhd directory

ver=`cat VERSION`
libhd=/tmp/libhd-$ver

make clean
rm -rf $libhd
mkdir $libhd
tar -cf - * | tar -C $libhd -xf -
cd $libhd
find . -depth -name CVS -exec rm -r {} \;
find . -depth -name .cvsignore -exec rm -r {} \;
cd src/ids
mkdir .x
mv Makefile.dist .x/Makefile
mv drivers.sample README* names.sample names.bus names.class mk_ids .x
rm *
mv .x/* .
rm -r .x
cd ../..
rm MAINTAINER scripts/ci_*
cd /tmp

tar -zcf $libhd.tar.gz libhd-$ver

if mkdir /work/src/done/STABLE/libhd ; then
  cd /work/src/done/STABLE/libhd
  cp $libhd.tar.gz /work/SRC/all/libhd/libhd.{changes,spec} .
  perl -pi -e 's/^(Version:\s+)\S+/${1}'$ver'/' /work/src/done/STABLE/libhd/libhd.spec
  perl -pi -e 's/^(Source.+?-)\S+?(\.tar\.gz)/${1}'$ver'${2}/' /work/src/done/STABLE/libhd/libhd.spec
  . /work/src/bin/.profile
  vc libhd
  rm /work/src/done/STABLE/libhd/*~
  echo "done"
else
  echo oops
  exit 1
fi

